### ISSUE TITLE
Search fields in German

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/raeber-website#14]
Dear @hanscools ,
I am currently developing the dynamic searchbox tool, is there a possibility to label all ressources in German as well in the ontology?

Thank you very much for your answer and best regards,
Jan

**Comment by hanscools** [comment]
Hi Jan,

Bit painful, I just see this only now... (linked to my private email).
Most of the elements have a German label too.
I'll complete it.

Regards,
Hans


On 08 Aug 2017, at 16:51, janCstoffregen wrote:

> Dear @hanscools ,
> I am currently developing the dynamic searchbox tool, is there a possibility to label all ressources in German as well in the ontology?
> 
> Thank you very much for your answer and best regards,
> Jan
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Hans Cools

**Comment by janCstoffregen** [comment]
Hi Hans,
no worries, I'm glad that there will be german labels as well!
Best regards,
Jan
