### ISSUE TITLE
Anpassung der API Constants in dev.ts

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/raeber-website#24]
Currently, the API - Parameter is defined as: 

````
  API: 'http://knora.nie-ine.ch/v1/search/',
````

This is used in the extended search in knora-api-params.ts. However, the api does not always contain /search/, for example when ressources are requested where the IRI is already known. I request to change the API constant accordingly and add the following constants:

````
  resourceTypesPath:  '/resourcetypes?vocabulary=',
  propertyListsQuery: '/propertylists?restype=',
  extendedSearch: '/search/?searchtype=extended&filter_by_restype=',
  extendedProperty: '&property_id=',
  compareOperator: '&compop=',
  searchval: '&searchval='

````

I don't do this myself because the extended search in knora.api.params will be affected, so I kindly assign Sebastian to rewrite the function if that's ok.

Unless this is done, I will keep the other constant declaration. We are not in a hurry to close this issue.

Best regards,
Jan

**Comment by sschuepbach** [comment]
Lieber @janCstoffregen , ich schaue mir die Sache an.

**Comment by sschuepbach** [comment]
Ich schlage vor, dass wir lediglich die root-URL zu unserer Knora-Instanz als Konstante in `dev.ts` haben. @janCstoffregen , würdest du es als sinnvoll erachten, wenn wir `knora-api-params.ts` so ausbauen würden, dass die vorgeschlagenen Konstanten als Elemente für Abfragen auf weitere Endpoints verwendet werden. D.h. also, dass `knora-api-params.ts` auch als factory für weitere Request-Typen gebraucht werden könnte?

**Comment by janCstoffregen** [comment]
Lieber Sebastian, 
das können wir gern machen, mir ist derzeit nur wichtig, dass alle Konstanten für die Abfragen an einem Ort sind und dass man sie in allen Komponenten benutzen kann.

**Comment by sschuepbach** [comment]
Lieber @janCstoffregen ,
ich habe soeben PR #37 erstellt, um die basalen Änderungen an dev.ts und knora-api-params.ts in den master einzuspeisen. Ich würde das Issue aber noch offen halten, um allfällige weitere Anpassungen hier zu diskutieren.

**Comment by sschuepbach** [comment]
Lieber @janCstoffregen, ich meine, dieses Issue ist definitiv obsolet, da wir für Knora v2 sowieso eine neue Implementierung machen müssen. Ich werde daher das Issue schliessen.
