### ISSUE TITLE
TypeError in textgrid.component.ts

### ISSUE THREAD

**Issue by sschuepbach** [nie-ine/raeber-website#27]
Lieber @janCstoffregen, lieber @rfbaumgartner 

ich kriege seit ein paar Tagen in den Ansichten, die `textgrid.component.ts` verwenden (Konvolut- und Synopsenansicht) eine Fehlermeldung:
```
ERROR TypeError: Cannot read property 'length' of undefined
    at TextgridComponent.ngOnChanges (textgrid.component.ts:29)
    at checkAndUpdateDirectiveInline (provider.ts:272)
    at checkAndUpdateNodeInline (view.ts:505)
    at checkAndUpdateNode (view.ts:443)
    at debugCheckAndUpdateNode (services.ts:377)
    at debugCheckDirectivesFn (services.ts:464)
    at Object.eval [as updateDirectives] (konvolut.component.html:35)
    at Object.debugUpdateDirectives [as updateDirectives] (services.ts:443)
    at checkAndUpdateView (view.ts:359)
    at callViewAction (view.ts:769)
```
Das Problem ist also, dass `chng.currentValue` noch keinen Wert zu dem Zeitpunkt hat, wenn dieser an `poemsInGrid` übergeben wird. Infolgedessen hat `poemsInGrid` auch keine Methode `length`.

Da ihr die Commits (34af1e35af8f0aad95b1df0c7acdf6ad59c125a7, bde38fbd1cb4e41a877914493fc2c8180dbb74bc) für die entsprechenden Zeilen geschrieben habt: Wäre es möglich, dass ihr euch das mal angucken könnt? Mein Problem ist, dass der Fehler zu weiterem unerwünschten Verhalten führt (bspw. kann ich Tabs in der Registerspalte oder Popups nicht mehr schliessen). Diese Fehler treten nicht auf, wenn ich die Zeilen auskommentiere.

Vielen Dank!

**Comment by rfbaumgartner** [comment]
Ich kenne mich mit `chng.currentValue` leider nicht aus. Keine Ahnung mehr, woher der Code kommt.

**Comment by rfbaumgartner** [comment]
Ich habe nochmal reingeschaut und einiges hat mit dem dynamischen Paginieren (https://github.com/nie-ine/raeber-website/commit/35588393634412e939b99919d665eaa6f7e19428) zu tun. Ich habe selbst damit schon Probleme gehabt und darum das onChanges eingegrenzt (https://github.com/nie-ine/raeber-website/commit/454ecb83b5bb3acd8050bf6cd1e5d798ad8461fa)

Die grosse Frage ist jetzt, ob wir das überhaupt brauchen. Wir haben ja keine Paginierung mehr vorgesehen.

**Comment by sschuepbach** [comment]
Lieber Reto
Der Code-Block wird immer dann ausgeführt, wenn eine Änderung an einer input property (einer property mit einem @input()-Dekorator) vorgenommen wird. Die Variable `chng` vom Type `SimpleChange` beinhaltet die Änderungen der property `poemsInGrid`. Der aktuelle Wert von `poemsInGrid` wird also `poemsInGrid` übergeben. Ich bin mir allerdings nicht sicher, ob es diesen Mechanismus überhaupt braucht, oder ob Angular automatisch die Werte von `poemsInGrid` bei einer Änderung aktualisiert.

Das Problem dürfte darin liegen, dass `poemsInGrid` erst dann einen Wert ungleich `undefined` hat, wenn der Request ein Ergebnis geliefert hat. Dies ist allerdings beim initialen Aufrufen der Methode `ngOnChanges` (das sogar vor `ngOnInit` erfolgt) mit ziemlicher Sicherheit noch nicht der Fall. Eine Lösung könnte eine Herangehensweise analog zu [diesem Codebeispiel](https://angular.io/guide/component-interaction#intercept-input-property-changes-with-ngonchanges) sein:
```
if (!chng.isFirstChange()) {
  this.poemsInGrid = chng.currentValue;
        for (this.i = 0; this.i < this.poemsInGrid.length; this.i++) {
          this.poemsInGrid[this.i].obj_id = encodeURIComponent(this.poemsInGrid[this.i].obj_id);
        }
}
```

**Comment by janCstoffregen** [comment]
Hi, ja, ich habe es auch gerade so versucht und es behebt meine Fehler, die ich seit kurzem hatte.

**Comment by sschuepbach** [comment]
Bei mir scheint es auch zu funktionieren. Wer möchte committen?

**Comment by sschuepbach** [comment]
#29
