### ISSUE TITLE
URLs für "Unterkonvolute" des ehemaligen Superkonvolutes "Abgewandt Zugewandt"

### ISSUE THREAD

**Issue by rpriber** [nie-ine/raeber-website#33]
Beim Mergen der Änderungen von @rfbaumgartner im branch "NIE-115..." in den master ist mir aufgefallen, dass mit dem Konvoluttyp und dem Inhalt von "text:hasAlias" bei den Links für die Unterkonvolute von "Abgewandt Zugewandt"
http://localhost:5555/drucke/hochdeutsche-gedichte
http://localhost:5555/drucke/alemannische-gedichte
rauskommt und nicht:
.../drucke/abgewandt-zugewandt-hochdeutsche-gedichte
.../drucke/abgewandt-zugewandt-alemannische-gedichte
Das passt aber nicht mehr zu den Abmachungen aus diesem Issue:
https://github.com/nie-ine/raeber-website/issues/9

Ist das ein Migrationsproblem, @sacha-alex, oder sollte der Link aus anderen Bestandteilen zusammengesetzt werden, @sschuepbach und @janCstoffregen?

**Comment by janCstoffregen** [comment]
Das ist kein Migrationsproblem, die Bezeichnungen für das Konvolut - Routing ist hardcodiert. Es ist eine Inkonsistenz, aber es sollte meiner Meinung nach keine Probleme bereiten. Ich kann es aber gern ändern, wenn es von jemandem gewünscht wird. Auch eine Änderung würde aber nichts ändern, da die Konvoluttitel, so wie sie im Routing vorkommen, sowieso nicht in der Ontologie vorkommen. Die routings werden also nur vollständig dynamisch bei der Fassungsansicht und bei der Synopsenansicht generiert.
