### ISSUE TITLE
Loading of Poems on Convolut page

### ISSUE THREAD

**Issue by Padlina** [nie-ine/raeber-website#42]
There is a bug during the loading of the poems, when selecting a Convolut from the menu:
- the first time you request it, no problem, the poems are loaded;
- but if you choose another Convolut from the menu, the poems will not be loaded;
- with a refresh, the poems are loaded.
Happy debugging ;)

**Comment by rfbaumgartner** [comment]
This sounds line ngOnInit instead of ngOnChanges because the component is not reloaded when navigating to a different convolute.

@janCstoffregen , I think you are already working on the poems in a convolute. Does it work on your branch?

**Comment by janCstoffregen** [comment]
Hi, yes, this will take more time, but now already different poems come for almost each convolut, see my next pull request, so I will close this issue for now. :)
