### ISSUE TITLE
Routing Problem

### ISSUE THREAD

**Issue by Padlina** [nie-ine/raeber-website#54]
On the "FassungsAnsicht", the routing for the previous (idOfPrev) and next poems (idOfNext) in the same convolute doesn't function.
The URL is correct and it does change in the URL adress bar, but the view doesn't change, that is the new view isn't rendered. The routes params also don't change. So, it seems a problem with routerlink.

These link are used twice:
- on the top of the view, in <rae-fassung-werkzeugleiste>
- at the bottom of the view, in <rae-fassung-blaettern>

To reproduce, check the branch "broken-routes", FassungsAnsicht, where there are two static links "HIER CLICKEN" and "HIER AUCH CLICKEN".

Happy Birthday Jan ;)

**Comment by rfbaumgartner** [comment]
With our routing, the Fassung component is always the same. It's just the parameters that change. To make it work, we need to observe parameter changes and load the data as needed.

At the current state ngOnInit only fires when the Fassung component is loaded the first time. Exporting the content of ngOnInit to a new function that is called through a new ngOnInit but also on parameter changes should solve the problem, in my opinion.

Edit: The subscription to the parameter has to be done once in the beginning obviously.

**Comment by janCstoffregen** [comment]
Fixed, with merge NIE-132.
So I'm closing this.
