### ISSUE TITLE
Überschriebene Variablen in Textgrid-Informationen

### ISSUE THREAD

**Issue by rfbaumgartner** [nie-ine/raeber-website#62]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Es gibt keine Synopsenlinks mehr im Textgrid und die Sortierung der Konvolute in den Registerspalten entspricht nicht mehr der Reihenfolge im Konvolut.
Grund ist, dass in `fromPoemIRIToTextgridInformation.component.ts` Variablen überschrieben worden sind.

**Expected behavior**

Die Variablen haben die gleichen Werte, wie zum Zeitpunkt als der Code geschrieben wurde.

**Minimal reproduction of the problem with instructions**

Navigiere zu einem Konvolut. Es sind keine Links zu Synopsen da.

**What is the motivation / use case for changing the behavior?**

Die Funktionalitäten müssen zurück.

**Comment by rfbaumgartner** [comment]
Können wir statt einem Array mit Index ein Map verwenden? Debuggen wird dann einfacher.

**Comment by rfbaumgartner** [comment]
Welche Informationen brauchen wir also?

- Gedichttitel
- CreationDate
- IRI
- sameEditionAs-IRIs (für Synopse)
- Restype (für Synopse)
- seqnum (für Konvolut und Registerspalte)
- WorkIRIs (für Synopsenlink im Konvolut)

ergänzt, wenn euch mehr einfallen

**Comment by rpriber** [comment]
Mir fallen noch ein:
- edierter Text
- Konvoluttitel (Synopse und Titelregister)

**Comment by Padlina** [comment]
The link to Synopse has been reintegred in the Convolute text-grid (with the merge of branch NIE-60). But I don't know about the sorting in Registerspalte: we still need to find out how to solve this.

**Comment by rfbaumgartner** [comment]
Sorting of the Registerspalte – later also for the convolute – can be done pretty fast. Everything it needs is described in commit https://github.com/nie-ine/raeber-website/pull/46/commits/b2d2af4040445861425fb563bf894adc903152ba

Shall we make a new branch for this or is there already a branch for such changes?

**Comment by Padlina** [comment]
I don't see a branch that we could use for this, so a new one I would say.

**Comment by rfbaumgartner** [comment]
Ok, I'm starting that

**Comment by rfbaumgartner** [comment]
The documentation and the freshly set parameters are now in the master.

If we merge new parameters early, probably even with a separate pull request, we can reduce the risk of conflicts in the future.
