### ISSUE TITLE
Error messaging in Suche on selecting convolute types

### ISSUE THREAD

**Issue by rfbaumgartner** [nie-ine/raeber-website#66]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

After a word search in the component Suche, selecting a convolut type triggers a message:
```
suche.component.html:17 ERROR TypeError: Cannot read property 'value' of null
    at SucheComponent.updateSuchmaskeKonvolutIRIMapping (suche.component.ts:542)
    at SucheComponent.handleSearchEvent (suche.component.ts:226)
```
It seems that selecting "Notizbücher" does not sort out typescripts (usually the ones in full caps in the title)

**Expected behavior**

No error message. Fewer poems on selecting convolutes.

**Minimal reproduction of the problem with instructions**

* Navigate to Suche
* search "Trümmer"
* click "Konvolute"
* click "Notizbücher"
* look at console

**Comment by janCstoffregen** [comment]
does not happen anymore
