### ISSUE TITLE
Bilder in keine guten Qualität in Fassungsansicht

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/raeber-website#77]
Bsp bei Gedicht Mittag (E) im Notizbuch 1979

Das muss sich noch ändern, vielleicht ist das auch bewusst so derzeit?

**Comment by rfbaumgartner** [comment]
Kann es sein, dass nur Thumbnails importiert sind? Sipi kann die Bilder nicht besser machen als sie sind und wenn man bei der Bildgrösse in der IIIF-Abfrage "full" eingibt, bleiben sie klein.

**Comment by rfbaumgartner** [comment]
Das Problem ist behoben
