### ISSUE TITLE
In der Konvolutsuche verschwinden die einzelnen cards, aber

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/raeber-website#80]
es rutschen keine nach, sodass leere zwischenfelder stehenbleiben.

Lieber Sebastian, kann ich Dir das assignen, da ihr das so schön bei der Synopse gelöst habt?

Danke für Deine Antwort und viele schöne Grüsse,
Jan

**Comment by sschuepbach** [comment]
Lieber Jan,
schaue ich mir gerne an.

**Comment by janCstoffregen** [comment]
ok, super, danke!

**Comment by sschuepbach** [comment]
Sollte mit PR #113 gelöst sein.
