### ISSUE TITLE
Routing für Konvolute mit zwei Ebenen (Abgewandt Zugewandt, Typoskripte spez., ...)

### ISSUE THREAD

**Issue by rfbaumgartner** [nie-ine/raeber-website#9]
Feature-Request

**Gegenwärtiges Verhalten**
Links lassen sich dynamisch aus Konvoluttyp, Konvolut-Routing-Element und im Falle von Gedichten dem Gedicht-Routing-Element zusammensetzen. Damit erreicht man die Mehrheit der Inhalte, aber bei zwei-Ebenen-Konvoluten sind das zu wenig Informationen und man kann die Links nicht konstruieren.

**Gewünschtes Verhalten**
Man kann bei jeden Gedicht oder Konvolut einfach einen gültigen Routing-Pfad rekonstruieren.

**Anweisungen um das Problem zu reproduzieren**
In Konvoluten wie `abgewandt-zugewandt/hochdeutsche-gedichte` lassen sich keine sauberen Links in der Registerspalte definieren (nur entweder für die Konvolutansicht oder die Fassungsansicht).

**Mögliche Lösung**
Auf die betroffenen Konvolute könnte man mit typ/konvolut (typ/konvolut/gedicht für die Gedichte) verlinken und die Linkst mit Hilfe der Routing-Module umleiten. 

Link: `/drucke/abgewandt-zugewandt/hochdeutsche-gedichte/107-einsicht`

Auszug aus Routing-Modul nach der Änderung:

```
      { path: 'drucke/hochdeutsche-gedichte', redirectTo: 'drucke/agewandt-zugewandt/hochdeutsche-gedichte'
      { path: 'drucke/abgewandt-zugewandt/:konvolut/:fassung', component: FassungComponent },
      { path: 'drucke/:konvolut/:fassung', component: FassungComponent },
```

**Motivation**
Für das Verlinken ergibt sich ein einheitliches Muster, das nur noch die notwendigsten Felder beinhaltet. Die Pfade bleiben bestehen und oberflächlich ändert sich nichts. 

**Bedingungen**
Die untergeordneten Konvolute haben den gleichen Typ wie die Konvolute, die nur eine Ebene haben.

**Comment by sschuepbach** [comment]
Vorab: Ich denke, dass Problem beschränkt sich auf die beiden Teile (alemannische und hochdeutsche Gedichte) von Abgewandt zugewandt. Für ähnlich gelagerte Fälle wie bspw. Notizbuch divers würde ich vorschlagen, den `notizbuch-divers`-Teil (oder analog) in der route wegzulassen, da solche Konvolute nicht inhärent miteinander verschränkt sind (zwei verschiedene, inhaltlich unabhängige Notizbücher vs. zwei Teile desselben Bandes).

Nichtsdestotrotz müssen wir natürlich eine Lösung für Abgewandt zugewandt finden. Grundsätzlich würde ich es schlecht finden, wenn wir eine programmatische Lösung für desen Sonderfall finden müssen, d.h., eine entsprechende Logik in die Konvolut-Komponente einbauen. Ich finde den Vorschlag von @rfbaumgartner grundsätzlich gut, bin aber nicht sicher, ob es nicht ein Problem gibt in `konvolut.component.ts`, konkret hier: https://github.com/nie-ine/raeber-website/blob/master/src/client/app/konvolute/konvolut/konvolut.component.ts#L49, wo auf den Parameter `konvolut` zugegriffen wird, der ja nach dem redirect nicht mehr vorhanden sein dürfte.

Daher wäre mein Vorschlag: `redirectTo` weglassen und die routes für die Konvolutansicht auf die alemannischen bzw. hochdeutschen Gedichten folgendermassen definieren: `drucke/abgewandt-zugewandt-alemannische-gedichte` und `drucke/abgewandt-zugewandt-hochdeutsche-gedichte` o.ä. Die Fassungen hätten dann die Form ` und `drucke/abgewandt-zugewandt-hochdeutsche-gedichte/fassungs-id`, womit hier wiederum die Trias `konvoluttyp/konvolut-id/fassungs-id` gewahrt wäre. Somit könnten wir den "Sonderfall" auf die Komponente `super-konvolut` beschränken, die ja sowieso spezifisch für Abgewandt zugewandt gebaut werden muss.

**Comment by rfbaumgartner** [comment]
Mit einem Problem mit `:konvolut` rechne ich nicht, da ja nach dem Redirect der Pfad neu gematcht wird. Bei redirectTo kann (muss?) der Pfad explizit sein, aber beim Ziel dieses Redirects kann die Variable wieder stehen.

Wenn wir `drucke/abgewandt-zugewandt-alemannische-gedichte` in den Pfad setzen, ist das Problem von Seiten der Webentwicklung praktisch gelöst und dafür muss dann beim Import das Routing-Element entsprechend verändert werden.

Den Vorschlag, `notizbuch-divers` aus dem Routing fallen zu lassen, finde ich gut. Das Routing orientiert sich dann eher an der DB statt an der Navitationsleiste, was doch auch langfristig der bessere Orientierungspunkt ist. Die Konvolutgruppen werden auch weiterhin durch die Navigation gemacht.

An einem Punkt gibt es aber Auswirkungen: Falls die Suche in Konvoluten die Konvolutgruppen beachten soll, dann müssen wir diese dort definieren. Sobald natürlich die Konvolute in den Gruppen nichts miteinander zu tun haben, kann man durchaus entgegnen, dass man dann halt jedes einzeln durchsuchen soll.  
Bei Abgewandt Zugewandt wird eine gemeinsame Suche nicht viel Sinn machen, da dort verschiedene Sprachvarietäten vorliegen.
