### ISSUE TITLE
eim Aufruf einer Fassung bleibt Konvolutseite bestehen oder wird nach unten geschoben

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/raeber-website#97]
Beim Aufruf einer Fassung bleibt Konvolutseite bestehen oder wird nach unten geschoben

**Comment by janCstoffregen** [comment]
@rfbaumgartner @sschuepbach @rpriber @Padlina @sacha-alex 
Liebes Team, ich kann dies derzeit nicht reproduzieren und weiss deshalb auch nicht, wie ich es beheben soll. Kann einer von euch es reproduzieren? Ist es vielleicht von allein weggegangen? :)

Vielen Dank für eure Antwort und viele schöne Grüsse,
Jan

**Comment by Padlina** [comment]
This happens only when there is an error somewhere. It is a side effect of an error, not a bug in itself.

**Comment by janCstoffregen** [comment]
ok, does it happen right now somewhere?

**Comment by janCstoffregen** [comment]
Please let me know if it happens somewhere, I have got the task to resolve it but can't find where it happens.

**Comment by rfbaumgartner** [comment]
I haven't seen it since the fixing of the register column. If it comes back it should probably be a new issue

**Comment by sschuepbach** [comment]
Can we close this issue? I neither encountered the described problem anymore after the fix of Reto.

**Comment by janCstoffregen** [comment]
ok, cool, thank you, I will close this issue for now, let's see if it comes back!
